version: '3.7'

services:
  currency-exchange:
    image: benkhanous/mmv3-currency-exchange-service:3.0.2
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
networks:
  currency-network: