version: '3.7'

services:
  currency-exchange:
    image: benkhanous/mmv3-currency-exchange-service:3.0.2
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

  naming-server:
    image: benkhanous/naming-server:0.0.1-SNAPHOST
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network: